-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 15:31:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PersonalSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PersonalSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PersonalSystem` DEFAULT CHARACTER SET utf8 ;
USE `PersonalSystem` ;

-- -----------------------------------------------------
-- Table `PersonalSystem`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`profiles` (
  `idProfile` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idProfile`),
  UNIQUE INDEX `nameUQ` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`lists` (
  `idlist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NOT NULL,
  `keyName` VARCHAR(45) NOT NULL,
  `locked` CHAR(1) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idlist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`listsValues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`listsValues` (
  `idListValue` INT NOT NULL AUTO_INCREMENT,
  `idList` INT NOT NULL,
  `idParent` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NOT NULL,
  `abbreviation` VARCHAR(45) NOT NULL,
  `position` VARCHAR(2) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idListValue`),
  INDEX `idListIDX` (`idList` ASC),
  INDEX `idParentIDX` (`idParent` ASC),
  INDEX `nameIDX` (`name` ASC),
  CONSTRAINT `idList_listsValues_lists_fk`
    FOREIGN KEY (`idList`)
    REFERENCES `PersonalSystem`.`lists` (`idlist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idParent_listsValues_listsValues_fk`
    FOREIGN KEY (`idParent`)
    REFERENCES `PersonalSystem`.`listsValues` (`idListValue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`persons` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `idCity` INT NULL,
  `idTypeDocument` INT NULL,
  `idDocument` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `secondName` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NOT NULL,
  `secondSurname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cellPhoneNumber` VARCHAR(45) NULL,
  `postalCode` VARCHAR(45) NULL,
  `dateBirth` DATE NULL,
  `address` VARCHAR(200) NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idPerson`),
  INDEX `idCityIDX` (`idCity` ASC),
  INDEX `idDocumentIDX` (`idTypeDocument` ASC),
  CONSTRAINT `idCity_persons_listsValues_fk`
    FOREIGN KEY (`idCity`)
    REFERENCES `PersonalSystem`.`listsValues` (`idListValue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idListValue_persons_listsValues_fk1`
    FOREIGN KEY (`idTypeDocument`)
    REFERENCES `PersonalSystem`.`listsValues` (`idListValue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `idProfile` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `lastEntry` DATE NULL,
  `attempts` INT(1) NOT NULL,
  `questions` INT NOT NULL,
  `condition` INT(1) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  `idPerson` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `nameUQ` (`name` ASC),
  INDEX `idProfileIDX` (`idProfile` ASC),
  INDEX `idPersonIDX` (`idPerson` ASC),
  CONSTRAINT `idProfile_users_profiles_fk`
    FOREIGN KEY (`idProfile`)
    REFERENCES `PersonalSystem`.`profiles` (`idProfile`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idPerson_users_persons_fk`
    FOREIGN KEY (`idPerson`)
    REFERENCES `PersonalSystem`.`persons` (`idPerson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`usersPasswords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`usersPasswords` (
  `idUserPassword` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idUserPassword`),
  INDEX `idUserIDX` (`idUser` ASC),
  CONSTRAINT `idUser_usersPasswords_users_fk`
    FOREIGN KEY (`idUser`)
    REFERENCES `PersonalSystem`.`users` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`usersQuestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`usersQuestions` (
  `idUserQuestion` INT NOT NULL,
  `idUser` INT NOT NULL,
  `question` VARCHAR(45) NOT NULL,
  `answer` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idUserQuestion`),
  INDEX `idUserIDX` (`idUser` ASC),
  CONSTRAINT `idUser_usersQuestions_users_fk`
    FOREIGN KEY (`idUser`)
    REFERENCES `PersonalSystem`.`users` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`actions` (
  `idAction` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NULL,
  `action` VARCHAR(45) NOT NULL,
  `position` VARCHAR(2) NOT NULL,
  `icon` VARCHAR(45) NULL,
  `class` VARCHAR(45) NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idAction`),
  UNIQUE INDEX `nameUQ` (`name` ASC),
  UNIQUE INDEX `actionUQ` (`action` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`icons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`icons` (
  `idIcon` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIcon`),
  UNIQUE INDEX `nameUQ` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`modules` (
  `idModule` INT NOT NULL AUTO_INCREMENT,
  `idParent` INT NULL,
  `idIcon` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idModule`),
  UNIQUE INDEX `nameUQ` (`name` ASC),
  INDEX `idIconIDX` (`idIcon` ASC),
  INDEX `idParentIDX` (`idParent` ASC),
  CONSTRAINT `idIcon_modules_icons_fk`
    FOREIGN KEY (`idIcon`)
    REFERENCES `PersonalSystem`.`icons` (`idIcon`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idParent_modules_modules_fk`
    FOREIGN KEY (`idParent`)
    REFERENCES `PersonalSystem`.`modules` (`idModule`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`menus` (
  `idMenu` INT NOT NULL AUTO_INCREMENT,
  `idModule` INT NULL,
  `idIcon` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NULL,
  `link` VARCHAR(45) NOT NULL,
  `actions` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idMenu`),
  UNIQUE INDEX `nameUQ` (`name` ASC),
  UNIQUE INDEX `linkUQ` (`link` ASC),
  INDEX `actionsIDX` (`actions` ASC),
  INDEX `idIconsIDX` (`idIcon` ASC),
  INDEX `idModuleIDX` (`idModule` ASC),
  CONSTRAINT `idIcon_menus_icons_fk`
    FOREIGN KEY (`idIcon`)
    REFERENCES `PersonalSystem`.`icons` (`idIcon`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idModule_menus_modules_fk`
    FOREIGN KEY (`idModule`)
    REFERENCES `PersonalSystem`.`modules` (`idModule`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`profilesMenus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`profilesMenus` (
  `idProfileMenu` INT NOT NULL AUTO_INCREMENT,
  `idProfile` INT NOT NULL,
  `idMenu` INT NOT NULL,
  `access` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idProfileMenu`),
  INDEX `idMenuIDX` (`idMenu` ASC),
  INDEX `idProfileIDX` (`idProfile` ASC),
  CONSTRAINT `idMenu_profilesMenus_menus_fk`
    FOREIGN KEY (`idMenu`)
    REFERENCES `PersonalSystem`.`menus` (`idMenu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idProfile_profilesMenus_profiles_fk`
    FOREIGN KEY (`idProfile`)
    REFERENCES `PersonalSystem`.`profiles` (`idProfile`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalSystem`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalSystem`.`settings` (
  `idSetting` INT NOT NULL AUTO_INCREMENT,
  `userFailedAttempts` INT NOT NULL,
  `daysWarningExpPass` INT NOT NULL,
  `minLongPass` INT NOT NULL DEFAULT 4,
  `maxLongPass` INT NOT NULL,
  `minUpperPass` INT NOT NULL,
  `minLowerPass` INT NOT NULL,
  `minSpecialCharsPass` INT NOT NULL,
  `charsAllowedPass` INT NOT NULL,
  `minNumPass` INT NOT NULL,
  `keyExpirDatePass` INT NOT NULL,
  PRIMARY KEY (`idSetting`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PersonalSystem`.`profiles`
-- -----------------------------------------------------
START TRANSACTION;
USE `PersonalSystem`;
INSERT INTO `PersonalSystem`.`profiles` (`idProfile`, `name`, `description`, `status`) VALUES (1, 'ADMINISTRADOR', NULL, '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PersonalSystem`.`persons`
-- -----------------------------------------------------
START TRANSACTION;
USE `PersonalSystem`;
INSERT INTO `PersonalSystem`.`persons` (`idPerson`, `idCity`, `idTypeDocument`, `idDocument`, `name`, `secondName`, `surname`, `secondSurname`, `email`, `cellPhoneNumber`, `postalCode`, `dateBirth`, `address`, `status`) VALUES (1, NULL, NULL, NULL, 'Carlos', NULL, 'Sosa', NULL, 'carlos@gmail.com', NULL, NULL, NULL, NULL, '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PersonalSystem`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `PersonalSystem`;
INSERT INTO `PersonalSystem`.`users` (`idUser`, `idProfile`, `name`, `email`, `lastEntry`, `attempts`, `questions`, `condition`, `status`, `idPerson`) VALUES (1, 1, 'carlos', 'carlos@gmail.com', NULL, 0, 0, 0, '1', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `PersonalSystem`.`usersPasswords`
-- -----------------------------------------------------
START TRANSACTION;
USE `PersonalSystem`;
INSERT INTO `PersonalSystem`.`usersPasswords` (`idUserPassword`, `idUser`, `password`, `startDate`, `endDate`, `status`) VALUES (1, 1, '12345', NULL, NULL, '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PersonalSystem`.`actions`
-- -----------------------------------------------------
START TRANSACTION;
USE `PersonalSystem`;
INSERT INTO `PersonalSystem`.`actions` (`idAction`, `name`, `description`, `action`, `position`, `icon`, `class`, `status`) VALUES (1, 'REGISTRAR', '\'\'', 'create', '1', NULL, NULL, '1');
INSERT INTO `PersonalSystem`.`actions` (`idAction`, `name`, `description`, `action`, `position`, `icon`, `class`, `status`) VALUES (2, 'MODIFICAR', '\'\'', 'update', '2', NULL, NULL, '1');
INSERT INTO `PersonalSystem`.`actions` (`idAction`, `name`, `description`, `action`, `position`, `icon`, `class`, `status`) VALUES (3, 'CONSULTAR', '\'\'', 'read', '3', NULL, NULL, '1');
INSERT INTO `PersonalSystem`.`actions` (`idAction`, `name`, `description`, `action`, `position`, `icon`, `class`, `status`) VALUES (4, 'INACTIVAR', '\'\'', 'inactivate', '4', NULL, NULL, '1');
INSERT INTO `PersonalSystem`.`actions` (`idAction`, `name`, `description`, `action`, `position`, `icon`, `class`, `status`) VALUES (5, 'ACTIVATE', '\'\'', 'activate', '5', NULL, NULL, '1');
INSERT INTO `PersonalSystem`.`actions` (`idAction`, `name`, `description`, `action`, `position`, `icon`, `class`, `status`) VALUES (6, 'REPORTE PDF', '\'\'', 'report_pdf', '6', NULL, NULL, '1');
INSERT INTO `PersonalSystem`.`actions` (`idAction`, `name`, `description`, `action`, `position`, `icon`, `class`, `status`) VALUES (7, 'REPORTE EXCEL', '\'\'', 'report_excel', '7', NULL, NULL, '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PersonalSystem`.`modules`
-- -----------------------------------------------------
START TRANSACTION;
USE `PersonalSystem`;
INSERT INTO `PersonalSystem`.`modules` (`idModule`, `idParent`, `idIcon`, `name`, `description`, `status`) VALUES (1, NULL, NULL, 'CONFIGURACIÓN DEL SISTEMA', NULL, '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PersonalSystem`.`menus`
-- -----------------------------------------------------
START TRANSACTION;
USE `PersonalSystem`;
INSERT INTO `PersonalSystem`.`menus` (`idMenu`, `idModule`, `idIcon`, `name`, `description`, `link`, `actions`, `status`) VALUES (1, 1, NULL, 'MÓDULOS', NULL, 'modules', '1,2,3,4,5,6', '1');
INSERT INTO `PersonalSystem`.`menus` (`idMenu`, `idModule`, `idIcon`, `name`, `description`, `link`, `actions`, `status`) VALUES (2, 1, NULL, 'MENÚS', NULL, 'menus', '1,2,3,4,5,6', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PersonalSystem`.`profilesMenus`
-- -----------------------------------------------------
START TRANSACTION;
USE `PersonalSystem`;
INSERT INTO `PersonalSystem`.`profilesMenus` (`idProfileMenu`, `idProfile`, `idMenu`, `access`, `status`) VALUES (1, 1, 1, '1,2,3,4,5', '1');
INSERT INTO `PersonalSystem`.`profilesMenus` (`idProfileMenu`, `idProfile`, `idMenu`, `access`, `status`) VALUES (2, 1, 2, '1,2,3,4,5', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PersonalSystem`.`settings`
-- -----------------------------------------------------
START TRANSACTION;
USE `PersonalSystem`;
INSERT INTO `PersonalSystem`.`settings` (`idSetting`, `userFailedAttempts`, `daysWarningExpPass`, `minLongPass`, `maxLongPass`, `minUpperPass`, `minLowerPass`, `minSpecialCharsPass`, `charsAllowedPass`, `minNumPass`, `keyExpirDatePass`) VALUES (1, 5, 15, 4, 12, 0, 2, 0, 0, 0, 30);

COMMIT;

